* se agrega comprobacion de root

diff --git a/refractainstaller-yad b/refractainstaller-yad
--- a/refractainstaller-yad
+++ b/refractainstaller-yad
@@ -1,6 +1,10 @@
 #!/bin/bash
 # Based on refractainstaller-8.0.3 by Dean Linkous
 LC_ALL=C
+if [[ $USER != root ]]; then
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
+fi
 error_log="/var/log/installer_error.log"
 miicono="--window-icon=/usr/share/icons/install-icon.png"
 rsync_excludes="/tmp/installer_exclude.list"
