* ultimos cambios

diff --git a/xanaduinstaller-yad b/xanaduinstaller-yad
--- a/xanaduinstaller-yad
+++ b/xanaduinstaller-yad
@@ -4,21 +4,21 @@
 # Based on refractainstaller-8.0.3 by Dean Linkous
 LC_ALL=C
 if [[ "$EUID" != "0" ]]; then
-	yad --window-icon=/usr/share/icons/install-icon.png --skip-taskbar --button=ACEPTAR:1 --fixed --center --text-align=fill --borders=6 --timeout=3 --title=ERROR --text="ERROR: Debes ser root."
-	exit 1
+	yad --window-icon=/usr/share/icons/install-icon.png --skip-taskbar --button=Aceptar:1 --fixed --center --text-align=fill --borders=6 --timeout=3 --title=ERROR --text="ERROR: Debes ser root."
+	exit 0
 fi
 if ! [[ -d /lib/live/mount/rootfs ]]; then
-	exit 1
+	exit 0
 fi
-[[ $DISPLAY ]] || { echo "No hay un servidor X corriendo. Saliendo..." ; exit 1 ; }
+[[ $DISPLAY ]] || { echo "No hay un servidor X corriendo. Saliendo..." ; exit 0 ; }
 
 trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
 echo "$BASHPID" > /run/"$(basename $0)".pid
 
-#wget -q -T 2 -O - https://raw.githubusercontent.com/sinfallas/xanadu-installer/master/xanaduinstaller-yad | sudo bash /dev/stdin
-#if [[ $? = 0 ]]; then
-#	exit 0
-#fi
+wget -q -T 2 -O - https://raw.githubusercontent.com/sinfallas/xanadu-installer/master/xanaduinstaller-yad | sudo bash /dev/stdin
+if [[ $? = 0 ]]; then
+	exit 0
+fi
 error_log="/var/log/installer_error.log"
 miicono="--window-icon=/usr/share/icons/install-icon.png"
 rsync_excludes="/tmp/installer_exclude.list"
@@ -69,7 +69,7 @@ function dialogopart () {
 		if [[ $? = 0 ]]; then
 			source /usr/bin/xanaduinstaller-yad
 		else
-			exit 1
+			exit 0
 		fi
 	fi
 	for i in $(fdisk -l "$dispositivo" | grep "swap" | awk '{print $1}'); do
@@ -134,7 +134,7 @@ function milvm () {
 	advert
 	$advertencia --text="Se recomienda utilizar un sistema de energia de respaldo para utilizar LVM"
 	if [[ $? != 0 ]]; then
-		exit 1
+		exit 0
 	fi
 	dialogopart
 	if [[ $(parted -s "$dispositivo" -- print | grep "Partition" | awk '{print $3}') = msdos ]]; then
@@ -319,7 +319,7 @@ function check_exit () {
 \Vea $error_log para detalles. \n\nEsto puede no ser fatal.. Presione \"Continuar\" para proceder"
 		if [[ $? != 0 ]]; then
 			cleanup
-			exit 1
+			exit 0
 		fi
 	fi
 }
@@ -416,7 +416,7 @@ function choose_boot () {
 		if [[ $? = 0 ]]; then
 			choose_boot
 		else
-			exit 1
+			exit 0
 		fi
 	fi
 }
@@ -611,7 +611,7 @@ if [[ $encrypt_os = "yes" ]] || [[ $encrypt_home = "yes" ]]; then
 			encrypt_os="no"
 			encrypt_home="no"
 		else
-			exit 1
+			exit 0
 		fi
 	fi
 fi    
@@ -639,7 +639,7 @@ if [[ $sep_boot = "no" ]]; then
 		if [[ $? = 0 ]]; then
 			encrypt_os="no"
 		else
-			exit 1
+			exit 0
 		fi
 	fi
 fi
@@ -664,7 +664,7 @@ choose_grub () {
 		elif ! [[ -b $grub_dev ]]; then
 			$errores --button="Salir":0 --button="Ir atras":1 --text="Algo esta mal.  $grub_dev no es un dispositivo de bloques."
 			if [[ $? = 0 ]]; then
-				exit 1
+				exit 0
 			else
 				choose_grub
 			fi
@@ -679,7 +679,7 @@ choose_grub () {
 		elif ! [[ -b $grub_partition ]]; then
 			$errores --button="Salir":0 --button="Ir atras":1 --text="Algo esta mal.  $grub_partition no es un dispositivo de bloques."
 			if [[ $? = 0 ]]; then
-				exit 1
+				exit 0
 			else
 				choose_grub
 			fi
@@ -724,14 +724,14 @@ choose_root () {
 		if [[ $? = 0 ]]; then
 			choose_root
 		else
-			exit 1
+			exit 0
 		fi
 #	elif ! [[ -b $install_dev ]]; then
 #    		$errores --button="Ir atras":0 --button="Salir":1 --text="    Algo esta mal. Tal vez usted marco mas de una casilla. Usted dijo que quiere instalar el sistema en: $install_dev"
 #        	if [[ $? = 0 ]]; then
 #            		choose_root
 #        	else
-#            		exit 1
+#            		exit 0
 #        	fi
 	elif [[ $install_dev = $boot_dev ]]; then
 		$errores --text="Selecciono la misma particion para la raiz y para /boot. Intente de nuevo." --button="Aceptar":0
@@ -762,7 +762,7 @@ el sistema operativo"
 		if [[ $? = 0 ]]; then
 			choose_fs_os
 		else
-			exit 1
+			exit 0
 		fi
 	fi  
 }
@@ -786,6 +786,14 @@ fi
 
 choose_home () {
 	home_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z][1-9]*" | sort | awk '{print "\n" $0 }' | yad $miicono --center --list --title="Particion para /home" --text="Seleccione una particion para /home" --separator="" --column ' ' --column 'Particiones' --height=400 --width=150 --button="Aceptar":0)
+	if [[ -z $home_dev ]]; then
+		$errores --button="Ir atras":0 --button="Salir":1 --text="No selecciono nada. Debe escoger una particion. Que quiere hacer?"
+		if [[ $? = 0 ]]; then
+			choose_home
+		else
+			exit 0
+		fi
+	fi
 	if [[ -n $home_dev ]]; then
 		if ! [[ -b $home_dev ]]; then
 			$errores --button="Ir atras":0 --button="Salir":1 --text="    Algo esta mal. 
@@ -793,7 +801,7 @@ choose_home () {
 			if [[ $? = 0 ]]; then
 				choose_home
 			else
-				exit 1
+				exit 0
 			fi
 		elif
 			[[ $install_dev = $home_dev ]]; then
@@ -801,7 +809,7 @@ choose_home () {
 			if [[ $? = 0 ]]; then
 				choose_home
 			else
-				exit 1
+				exit 0
 			fi
 		elif
 			[[ $boot_dev = $home_dev ]]; then
@@ -809,7 +817,7 @@ choose_home () {
 			if [[ $? = 0 ]]; then
 				choose_home
 			else
-				exit 1
+				exit 0
 			fi
 		fi
 	fi
@@ -831,7 +839,7 @@ choose_fs_home () {
 		if [[ $? = 0 ]]; then
 			choose_fs_home
 		else
-			exit 1
+			exit 0
 		fi
 	fi
 }
